schema-version = 1
release-version = "1.22.0"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[vendor.giinglis]
registry = "458358962224.dkr.ecr.us-west-2.amazonaws.com"

[sdk]
name = "bottlerocket-sdk"
version = "0.44.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "2.5.0"
vendor = "giinglis"
